url: https://iamtheib.me
# url: 127.0.0.1:4000

# Site settings
title: ibrahim sikiru (ib)
owner: ibrahim sikiru (ib)
description: "i am ibrahim sikiru, i am a computer science student, a software developer, a programmer, a coder, an entrepreneur, and an aspiring hacker"

# Contact
email:
    name: ib
    domain: iamtheib
    tld:  me
social:
  - icon: github
    url:   https://github.com/iamtheib
  - icon: linkedin
    url:   https://linkedin.com/in/iamtheib

# jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor:  uglifier
  css_compressor: sass
