url: https://iamtheib.me
# url: 127.0.0.1:4000

# Site settings
title: ib sikiru
owner: ib sikiru
description: "i am ib sikiru, a software developer, a programmer, an entrepreneur, an aspiring hacker, and a fan of lowercase characters"

# Contact
email:
    name: ib
    domain: iamtheib
    tld:  me
social:
  - icon: github
    url:   https://github.com/iamtheib
  - icon: linkedin
    url:   https://linkedin.com/in/iamtheib

# jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor:  uglifier
  css_compressor: sass
