#url: https://iamtheib.me
url: http://iamtheib.dev

# Site settings
title: ibrahim sikiru (iamtheib)
owner: ibrahim sikiru
description: "i am ibrahim sikiru, i am a computer science student, software engineering student, a coder, a programmer, a developer and an aspiring hacker"

# Contact
email:
    name: ib
    domain: iamtheib
    tld:  me
social:
  - icon: github
    url:   https://github.com/iamtheib
  - icon: linkedin
    url:   https://linkedin.com/in/iamtheib

# jekyll-assets
assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  js_compressor:  uglifier
  css_compressor: sass